### ISSUE TITLE
npm install mustache@0.5.1-dev installs 0.5.2 version instead

### ISSUE THREAD

**Issue by ONE001** [janl/mustache.js#536]
After installing it says mustache@0.5.1-dev node_modules/mustache 
but when i look into node_modules/mustache/mustache.js there is a line exports.version = "0.5.2" and the behavior like it is 0.5.2

**Comment by phillipj** [comment]
@ONE001 v0.5.2 are more than 3 years old now, you would get more support by the community by using a more recent version. Any reason you're not using the current stable version, v2.2.1?

**Comment by dasilvacontin** [comment]
@ONE001 That's how the code was released – even if the `package.json` has a `0.5.1-dev` value for `version`, the code already has a `0.5.2` value for `version`. There's not even a tag for such version in GitHub. ¯_(ツ)_/¯

Closing since there was no followup to @phillipj's question and I can't really see anything we can do about the issue.
