### ISSUE TITLE
mustache time complexity

### ISSUE THREAD

**Issue by arielorvits** [janl/mustache.js#709]
Hi, where can I find some general details about mustache time complexity or algorithm details (without dive into the code)?

how the size of the template / dictionary influence the time complexity?

thanks!

**Comment by phillipj** [comment]
Can't seem to remember having encountered what you're asking for I'm afraid. Historically I've stumbled upon some performance benchmarks done with the intention of comparing different templating engines and their raw performance, but those would be very misleading today because they were created a long time ago, and it wouldn't really answer your question anyways.

I would happily assist in digging into any concrete performance issues if you have any. But I'm surely not the best suited developer to write those kinds of general details about the algorithm chosen and how performance gets degraded based off of different factors.

**Comment by phillipj** [comment]
Closing this for now as there's no clear answer to your questions ATM.

If anyone with the necessary knowhow and interests would like to dive into this, that would surely be interesting to see the outcome of.
