### ISSUE TITLE
The tick mark is rendered to be &#x60;

### ISSUE THREAD

**Issue by tianhaoz95** [janl/mustache.js#720]
I recently found that when the text I want to render contains tick marks, it will be rendered to `&#x60;` for some reason. I am wondering if this is the designed behavior.

**To reproduce**

```js
const snippet = "This snippet has `tick marks` in it";
const template = "The snippet I want: {{snippet}}, it doesn't look right.";
const rendered = mustache.render(template, { snippet });
// The rendered output replaces ` with &#x60; for some reason.
```

If this is the designed behavior, what is the work around if I want to render tick marks other than do a replace after the result has been rendered.

Thanks for the awesome package :)

**Comment by phillipj** [comment]
Hi there!

Yes, the escaping is by design so to speak, it's part of the [mustache spec](https://mustache.github.io/mustache.5.html).

All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: `{{{name}}}`.

You can also use `&` to unescape a variable: `{{& name}}`.

Does that answer your question?

**Comment by tianhaoz95** [comment]
ohhh I see. yes! that answers my question! Thanks so much!
