### ISSUE TITLE
Intenal cache increases with dynamic html content

### ISSUE THREAD

**Issue by gomezbl** [janl/mustache.js#748]
Hi there, first of all, thanks for this amazing module I used long time ago.
I found something that may be is happening to other developers.
I use Mustache.render and Mustache.parse, and in my production enviroment (www.hubdelibros.com), I found an important memory leak. After investigating, I found the problem was in Mustache internal cache (this.templateCache). That cache uses the template as a key.
But.... in my system, many templates are dinamically generated with forms elements which Ids are UUIDS, so, 1000 requests generate 1000 different html content (different ids in some elements). Due to this, Mustache internal cache increases ad infinitum.
I solved this calling Mustacle.clearCache() in every request.
Is there a better way to disable that internal cache?
Thanks in advance.

**Comment by phillipj** [comment]
Hi @gomezbl!

Thanks for reporting 👍 Our template cache surely has its limitations, which is why we quite recently made sure it can easily be customized.

And guess what, you're in luck, as one of the things we aimed for was being able to completely disable the cache completely 😸 

Have a look at v4.0.0 changelog and shout if that doesn't cover your needs: [CHANGELOG/v4.0.0](https://github.com/janl/mustache.js/blob/master/CHANGELOG.md#400--16-january-2020).

**Comment by gomezbl** [comment]
Ok, thanks a lot.
