### ISSUE TITLE
Proposal: Instream Parameters enhancement

### ISSUE THREAD

**Issue by srp7474** [janl/mustache.js#759]
I have dropped a working enhancement into Actions.  It allows parameters to be passed to a function.  I found it very useful to act as conditional logic and to write an HTML generator that connected the generated HTML to the javascript supporting code.

I was not sure how if the pull request was performed the correct way. The code modification is about a dozen lines to Mustache.js plus the section added to README.md.

It may also be an implementation of issue #677

**Comment by phillipj** [comment]
Hi @srp7474!

Cool to see you've come up with some really handy modifications that could be really useful for others as well, thanks for sharing 👍 

I'll be honest and say I'm hesitant merging them primarily because of one reason; mustache.js is supposed to be a pure JavaScript implementation of the [mustache spec](https://mustache.github.io/mustache.5.html). That's both good and bad, it works perfectly for many but lacks a lot of trivial features for others.

In practise that means syntax wise there isn't much room creativity for things not part of the mustache spec. I believe implementations in other languages, such the PHP equivalent, has introduced a concept in its core that allows anyone to extend the mustache syntax without touching the core library, called "pragma"s I believe. Sadly we haven't come to introducing that in mustache.js yet, but for me personally that's the sensible way to introduce unofficial syntax or features.

Would love ideas on how to communicate this properly in our README.md, which could have helped set your (and future contributors) expectations earlier.

**Comment by srp7474** [comment]
Thanks Phillip for your input. What you said makes sense in the overall scheme of things.
