### ISSUE TITLE
Can't replace mustache tag inside <script></script>

### ISSUE THREAD

**Issue by pgiouroukis** [janl/mustache.js#761]
I would like to be able to write a custom script for every render of the template, so I did the following:
<script>{{myCustomScript}}</script>
And then I replace "myCustomScript" with the code I want (as a string).
But it does not seem to work. Any ideas?

**Comment by phillipj** [comment]
My first gut reaction would be to try `{{{myCustomScript}}}` instead, because that would avoid the default HTML escaping of values that mustache.js does out of the box.

> But it does not seem to work. Any ideas?

What does not work? For anyone to chime in with helpful thoughts or tips-n-tricks, it's important for you to provide as concrete examples as possible.

**Comment by phillipj** [comment]
Closing this for now due to lack from the author, don't hesitate to re-open if this is still an issue.
