### ISSUE TITLE
Is it possible to set mustache as view engine?

### ISSUE THREAD

**Issue by ramseth001** [janl/mustache.js#791]
When I did this 

`app.set("view engine", "mustache");`

I got this error

> Error: Module "mustache" does not provide a view engine.

Also, I could not find "mustache" in this [list](https://expressjs.com/en/resources/template-engines.html) from Express website.

**Comment by phillipj** [comment]
mustache.js is not directly compatible with express.js, no.

There has to be something in between, that knows how to work as a view engine for express.js and at the same time knows how to use mustache.js.

I've used something like [consolidate.js](https://github.com/tj/consolidate.js) in the past for this. Whether or not it still does the trick, or if better alternatives has been created, I honestly don't know.

Closing this issue since it's not an issue with mustache.js itself.
